networks:
    default:
        name: horizon-test

services:
    base:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
        image: sail-8.4/app
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        volumes:
            - '.:/var/www/html'
        ports:
            - 9999:80

    redis:
        image: redis:7
        volumes:
            - redis:/data
        ports:
            - 9998:6379

volumes:
    redis:
